title: Jdollar-j-
description:  JDollar is a  ASIAN  highly standard and  securable Programming Language invented   in CH$ P.L
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
